<a href="https://colab.research.google.com/github/Ardalan-gerami81/HW_ML/blob/main/Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import cvxpy as cp

In [20]:
n_1 = 1
n_2 = 1
n_3 = 1
n = n_1 + n_2 + n_3
S = np.ones((n_1+n_2, n_1+n_2))
T = np.ones((n_2+n_3, n_2+n_3))
R = cp.Variable((n, n), PSD=True)
R1 = R[0:2, 0:2]
R2 = R[1:3, 1:3]
R_13 = R[0, 2]

In [9]:
objective = cp.Minimize(cp.norm(R1 - S, "fro")**2 + cp.norm(R2 - T, "fro")**2 +cp.norm(R_13, "fro")**2)
# now we should recover R due to part
p = cp.Problem(objective, [])
p.solve()
print('Optimal value:')
print(p.value)
print('Recovered covariance matrix R')
print(str(R.value))
print('Eigenvalues')
print(str(np.linalg.eig(R.value)[0]))

Optimal value:
0.17484495311647527
Recovered covariance matrix R
[[1.09855076 0.84973176 0.19710124]
 [0.84973176 1.11456302 0.84973176]
 [0.19710124 0.84973176 1.09855076]]


In [18]:
# now we check that R id psd or not
print('Eigenvalues')
print(str(np.linalg.eig(R.value)[0]))

Eigenvalues
[ 2.41021598e+00  9.01449521e-01 -9.60079861e-07]
